/**
 * SEMANTIC CAPABILITIES
 * Deterministic mapping of event subtypes to functional narrative capabilities.
 * This absorbs linguistic variation (e.g. reading vs hearing) into structural logic.
 */

export const CAPABILITIES = {
  EMITS_CONTENT: "EMITS_CONTENT",       // Speaking, writing, showing
  RECEIVES_CONTENT: "RECEIVES_CONTENT", // Being told, handed a note
  PERCEIVES_CONTENT: "PERCEIVES_CONTENT", // Reading, observing, noticing
  PHYSICAL_CONTROL: "PHYSICAL_CONTROL", // Holding, taking, securing
  TRANSIT: "TRANSIT",                   // Moving, arriving, leaving
  OBSTRUCTS: "OBSTRUCTS",               // Blocking, attacking, destroying
  
  // DELIVERY CHANNEL SEMANTICS
  DELIVERS_TO_TARGET: "DELIVERS_TO_TARGET", // Directed delivery (e.g. "told him")
  BROADCAST_VISIBLE: "BROADCAST_VISIBLE",   // Accessible to any observer (e.g. "said aloud")
  PRIVATE_EMISSION: "PRIVATE_EMISSION",     // Inaccessible (e.g. "muttered", "thought")

  // NEGATIVE/MODAL SEMANTICS
  BLOCKS_TRANSFER: "BLOCKS_TRANSFER",       // Explicit obstacle
  REFUSES: "REFUSES",                       // Character rejects the action/info
  WITHHOLDS_CONTENT: "WITHHOLDS_CONTENT"    // Explicit silence or secrecy
};

export const SUBTYPE_CAPABILITY_MAP = {
  DIALOGUE_EXPLICIT: [CAPABILITIES.EMITS_CONTENT, CAPABILITIES.BROADCAST_VISIBLE],
  DIALOGUE_IMPLICIT: [CAPABILITIES.EMITS_CONTENT, CAPABILITIES.BROADCAST_VISIBLE, CAPABILITIES.REFUSES, CAPABILITIES.WITHHOLDS_CONTENT],
  REVEAL_EXPLICIT: [CAPABILITIES.EMITS_CONTENT, CAPABILITIES.BROADCAST_VISIBLE],
  REVEAL_IMPLICIT: [CAPABILITIES.EMITS_CONTENT, CAPABILITIES.PRIVATE_EMISSION],
  DOCUMENT_READ: [CAPABILITIES.PERCEIVES_CONTENT, CAPABILITIES.RECEIVES_CONTENT],
  SENSORY_OBSERVATION: [CAPABILITIES.PERCEIVES_CONTENT, CAPABILITIES.RECEIVES_CONTENT],
  OBJECT_MANIPULATION: [CAPABILITIES.PHYSICAL_CONTROL, CAPABILITIES.EMITS_CONTENT, CAPABILITIES.BROADCAST_VISIBLE],
  PHYSICAL_MOVEMENT: [CAPABILITIES.TRANSIT],
  THRESHOLD_CROSS: [CAPABILITIES.TRANSIT],
  VIOLENCE_EXECUTION: [CAPABILITIES.OBSTRUCTS, CAPABILITIES.BLOCKS_TRANSFER],
  MECHANISM_TRIGGER: [CAPABILITIES.OBSTRUCTS, CAPABILITIES.PHYSICAL_CONTROL],
  GESTURE_ACK: [CAPABILITIES.PERCEIVES_CONTENT, CAPABILITIES.RECEIVES_CONTENT],
  EMOTIONAL_DISPLAY: [CAPABILITIES.PERCEIVES_CONTENT, CAPABILITIES.RECEIVES_CONTENT],
  VISUAL_DESCRIPTOR: [CAPABILITIES.PERCEIVES_CONTENT],
  SECRET_REVEAL: [CAPABILITIES.EMITS_CONTENT, CAPABILITIES.BROADCAST_VISIBLE],
};

/**
 * Enriches an extracted event with its semantic capabilities.
 */
export function enrichEventCapabilities(event) {
  const caps = SUBTYPE_CAPABILITY_MAP[event.subtype] || [];
  return { ...event, capabilities: caps };
}
