export const CRITIC_CHALLENGE_SET = [
  {
    id: "bad-01",
    bucket: "obviously_bad",
    expectedVerdict: "REWRITE",
    notes: "Abstract emotion and generic pressure words.",
    text: "He felt very sad and everything was overwhelming.",
  },
  {
    id: "bad-02",
    bucket: "obviously_bad",
    expectedVerdict: "REWRITE",
    notes: "Clean grammar, empty content, no specificity.",
    text: "The room was nice and the atmosphere felt strange in a way he could not explain.",
  },
  {
    id: "bad-03",
    bucket: "obviously_bad",
    expectedVerdict: "REWRITE",
    notes: "Overexplaining and generic summary.",
    text: "She was scared because the moment felt wrong, and the fear made her realize how dangerous the whole situation really was.",
  },
  {
    id: "bad-04",
    bucket: "obviously_bad",
    expectedVerdict: "REWRITE",
    notes: "Flat rhythm and low detail.",
    text: "He walked down the hall. He looked around. He was nervous. It was bad.",
  },
  {
    id: "mid-01",
    bucket: "borderline_mid",
    expectedVerdict: "REWRITE",
    notes: "Competent sentence, still soft and generic.",
    text: "Rain glazed the windows while Mara stared at the file and tried to steady her breathing before she made the call.",
  },
  {
    id: "mid-02",
    bucket: "borderline_mid",
    expectedVerdict: "REWRITE",
    notes: "Readable, but emotionally labeled and safe.",
    text: "Jon was angry, though he kept his voice calm as he asked where the missing money had gone.",
  },
  {
    id: "mid-03",
    bucket: "borderline_mid",
    expectedVerdict: "REWRITE",
    notes: "Deceptively clean but thin.",
    text: "The city below looked immense, and for a moment Lina understood how small her own plans had been.",
  },
  {
    id: "mid-04",
    bucket: "borderline_mid",
    expectedVerdict: "REWRITE",
    notes: "Decent cadence, weak sensory grip.",
    text: "He opened the letter slowly, already knowing the news would change things, though he could not yet say how.",
  },
  {
    id: "mid-05",
    bucket: "borderline_mid",
    expectedVerdict: "REWRITE",
    notes: "Clean prose, empty nouns, safe tone.",
    text: "The meeting carried a tension everyone noticed, but no one wanted to be the first to disturb the fragile calm.",
  },
  {
    id: "clean-empty-01",
    bucket: "deceptively_clean_empty",
    expectedVerdict: "REWRITE",
    notes: "Polished but content-free.",
    text: "There was something unforgettable about the morning, something that seemed to gather all the important parts of life into a single quiet moment.",
  },
  {
    id: "clean-empty-02",
    bucket: "deceptively_clean_empty",
    expectedVerdict: "REWRITE",
    notes: "Abstract significance without detail.",
    text: "In that instant, everything changed, though the nature of the change would only become clear much later.",
  },
  {
    id: "clean-empty-03",
    bucket: "deceptively_clean_empty",
    expectedVerdict: "REWRITE",
    notes: "Smooth cadence disguising generic language.",
    text: "The night seemed to hold its breath around them, full of meaning neither of them could quite name.",
  },
  {
    id: "strong-01",
    bucket: "actually_strong",
    expectedVerdict: "APPROVE",
    notes: "Concrete physical detail and pressure.",
    text: "By the time Noor got the key into the archive door, the cut across her knuckles had glued three fingers together with blood, and the brass bit into her palm every time the lock slipped.",
  },
  {
    id: "strong-02",
    bucket: "actually_strong",
    expectedVerdict: "APPROVE",
    notes: "Specificity, rhythm, and emotional concreteness.",
    text: "Eli read the verdict once, twice, then laid the paper flat on the sink because his hands had started to shake hard enough to tear the wet corner clean off.",
  },
  {
    id: "strong-03",
    bucket: "actually_strong",
    expectedVerdict: "APPROVE",
    notes: "Distinct image and tonal control.",
    text: "The generator coughed awake under the floorboards, a diesel animal clearing its throat, and the lights came back one strip at a time along the corridor.",
  },
  {
    id: "strong-04",
    bucket: "actually_strong",
    expectedVerdict: "APPROVE",
    notes: "Physical reaction instead of abstract labeling.",
    text: "When her father said the house was sold, Vera smiled first, out of habit, then tasted the copper where she'd bitten the inside of her cheek too hard.",
  },
];
